In [2]:
from pathlib import Path
import librosa
import pandas as pd
import numpy as np
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from rimworld import rimjobs, rimsound, utils

In [3]:

data_folder = Path(f"../data/nsynth-test/")
metadata = utils.read_metadata(data_folder)  
one_row = pd.DataFrame(metadata.iloc[0]).T
one_row

,qualities,pitch,note,instrument_source_str,velocity,instrument_str,instrument,sample_rate,qualities_str,instrument_source,note_str,instrument_family,instrument_family_str
bass_synthetic_068-049-025,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]",49,217499,synthetic,25,bass_synthetic_068,656,16000,[dark],2,bass_synthetic_068-049-025,0,bass

In [7]:

wave_file = (data_folder / 'audio' / 'bass_synthetic_068-049-025').with_suffix(".wav")

def _get_row_stft(row):

    y, sr = librosa.load(wave_file, sr=16000)

    s = librosa.stft(y, n_fft=2048)

    s = np.around(s, decimals=0, out=None)


    return pd.Series(s)

# stft = _get_row_stft(wave_file)
# stft
# spectra = one_row.apply(_get_row_stft, axis=1)
# one_row.join(spectra)
def spectrum(row):
    stft = rimsound.RimSound \
        .from_wav(wave_file, 16000, n_fft=2048) \
        .get_spectrum()
    return stft
spectra = one_row.apply(spectrum, axis=1)
one_row.join(spectra)

,qualities,pitch,note,instrument_source_str,velocity,instrument_str,instrument,sample_rate,qualities_str,instrument_source,...,7929.6875,7937.5,7945.3125,7953.125,7960.9375,7968.75,7976.5625,7984.375,7992.1875,8000.0
bass_synthetic_068-049-025,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]",49,217499,synthetic,25,bass_synthetic_068,656,16000,[dark],2,...,0.041883,0.053673,0.037878,0.02319,0.027198,0.023874,0.022928,0.026025,0.026581,0.019708

In [46]:
data_folder = Path(f"../data/nsynth-test/")
metadata = utils.read_metadata(data_folder)  
one_row = pd.DataFrame(metadata.iloc[0]).T
one_row

,qualities,pitch,note,instrument_source_str,velocity,instrument_str,instrument,sample_rate,qualities_str,instrument_source,note_str,instrument_family,instrument_family_str
bass_synthetic_068-049-025,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]",49,217499,synthetic,25,bass_synthetic_068,656,16000,[dark],2,bass_synthetic_068-049-025,0,bass

In [11]:
wave_file = (data_folder / 'audio' / 'bass_synthetic_068-049-025').with_suffix(".wav")


def raw(row):
    y, sr = librosa.load(wave_file, sr=16000)
    return pd.Series(y)
raw_audio = one_row.apply(raw, axis=1)
one_row=one_row.join(raw_audio)

In [15]:
one_row.iloc[:,4013:4025]

,4000,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011
bass_synthetic_068-049-025,0.159637,0.169159,0.175476,0.178131,0.176697,0.170807,0.160309,0.145203,0.12558,0.101593,0.073822,0.042694